config/routes.rb
Rails.application.routes.draw do

  get '/follow/:id' => 'follows#create', :as => 'follow_new'
  delete '/follow/:id' => 'follows#destroy', :as => 'follow_destroy'

  get 'follows/index'
  get 'follows/show'

  root :to => 'pages#home'

  resources :doodles, :artists

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :text
#  location   :text
#  dob        :date
#  avatar     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Artist < ActiveRecord::Base
  has_many :doodles
  has_many :active_relationships, class_name: 'Follow', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Follow', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :following, through: :active_relationships, source: :followed

  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  validates :blurb, :length => {:maximum => 100}
end

app/models/doodle.rb
# == Schema Information
#
# Table name: images
#
#  id         :integer          not null, primary key
#  title      :text
#  url        :text
#  caption    :text
#  artist_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Doodle < ActiveRecord::Base
  belongs_to :artist
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower, class_name: "Artist"
  belongs_to :followed, class_name: "Artist"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :fetch_user

  private
  def fetch_user
    if session[:artist_id].present?
      @current_artist = Artist.find_by :id => session[:artist_id]
    end
    session[:artist_id] = nil unless @current_artist.present?
  end

  def check_for_user
    redirect_to root_path unless @current_artist.present?
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create

    artist = Artist.new artist_params

    if params[:file].present?
      # Then call Cloudinary's upload method, passing in the file in params
      req = Cloudinary::Uploader.upload(params[:file])
      # Using the public_id allows us to use Cloudinary's powerful image transformation methods.
      artist.avatar = req["public_id"]
    end

    if artist.save
      session[:artist_id] = artist.id
      redirect_to artist
    else
      render  :edit
    end

  end

  def edit
    @artist = Artist.find params[:id]
    redirect_to root_path unless @current_artist.id == @artist.id
  end

  def update
    artist = Artist.find params[:id]
    redirect_to root_path unless @current_artist.id == artist.id

    if params[:file].present?
      # Then call Cloudinary's upload method, passing in the file in params
      req = Cloudinary::Uploader.upload(params[:file])
      # Using the public_id allows us to use Cloudinary's powerful image transformation methods.
      artist.avatar = req["public_id"]
    end

    artist.update_attributes artist_params   # get the fields from the submitted form

    if artist.save
      redirect_to artist
    else
      render  :edit
    end

  end

  def show
    @artist = Artist.find params[:id]
    @doodles = Doodle.where :artist_id => params[:id]
  end

  def destroy
    artist = Artist.find params[:id]
    artist.destroy
    redirect_to artists_path
  end

  private
  def artist_params
    params.require(:artist).permit(:name, :location, :dob, :email, :password, :password_confirmation, :blurb)
  end
end

app/controllers/doodles_controller.rb
class DoodlesController < ApplicationController
  def index
    @doodles = Doodle.all   #TODO: .where( :public => true )
  end

  def new
    @doodle = Doodle.new
  end

  def create
    doodle = @current_artist.doodles.create doodle_params
    if params[:file].present?
      # Then call Cloudinary's upload method, passing in the file in params
      req = Cloudinary::Uploader.upload(params[:file])
      # Using the public_id allows us to use Cloudinary's powerful image transformation methods.
      doodle.image_url = req["public_id"]
      if doodle.save
        redirect_to doodle
      else
        render :new
      end
    end
  end

  def edit
    @doodle = Doodle.find params[:id]
    redirect_to doodles_path unless @current_artist.id == @doodle.artist_id
  end

  def update
    doodle = Doodle.find params[:id]
    redirect_to doodles_path unless @current_artist.id == doodle.artist_id
    doodle.update doodle_params
    redirect_to doodle
  end

  def show
    @doodle = Doodle.find params[:id]
  end

  def destroy
    doodle = Doodle.find params[:id]
    redirect_to doodles_path unless @current_artist.id == doodle.artist_id
    doodle.destroy
    redirect_to doodles_path
  end

  private
  def doodle_params
    params.require(:doodle).permit(:title, :caption)
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  before_action :check_for_user, :only => [:create, :destroy]

  def create
    follow = Follow.create :follower_id => @current_artist.id, :followed_id => params[:id]
    flash[:message] = 'You are now following this doodler.'
    redirect_to artist_path( params[:id] )
  end

  def destroy
    follow = Follow.where(:follower_id => @current_artist.id, :followed_id => params[:id]).destroy_all
    redirect_to artist_path( params[:id] )
  end

  def index
  end

  def show
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end


  def create
    artist = Artist.find_by :email => params[:email]
    if artist.present? && artist.authenticate(params[:password])
      session[:artist_id] = artist.id
      redirect_to root_path
    else
      flash[:message] = 'Invalid username or password. Please try again.'
      redirect_to login_path
    end
  end


  def destroy
    session[:artist_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/doodle_helper.rb
module DoodleHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/artist/edit.html.erb
<h1>Artist#edit</h1>
<p>Find me in app/views/artist/new.html.erb</p>

app/views/artist/new.html.erb
<h1>Artist#new</h1>
<p>Find me in app/views/artist/new.html.erb</p>

app/views/artists/_form.html.erb
<%= form_for(@artist, :html => {:multipart => true}) do |f| %>

<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :avatar %>
  <%= f.cl_image_upload :avatar %>
</p>

<p>
  <%= f.label :dob %>
  <%= f.date_field :dob %>
</p>

<p>
  <%= f.label :location %>
  <%= f.text_field :location %>
</p>


  <p>
    <%= f.label :blurb %>
    <%= f.text_area :blurb, :id => 'artist_blurb', :maxlength => 100 %>
  </p>


  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>


  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>

  <%= f.submit 'Sign up!' %>
<% end %>

app/views/artists/create.html.erb
<h1>Artist#create</h1>
<p>Find me in app/views/artist/create.html.erb</p>

app/views/artists/destroy.html.erb
<h1>Artist#destroy</h1>
<p>Find me in app/views/artist/destroy.html.erb</p>

app/views/artists/edit.html.erb
<h1>Edit Profile</h1>

<% if @artist.errors.any? %>
  <ol>
    <% @artist.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for(@artist, :html => {:multipart => true}) do |f| %>
  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :avatar %>
    <%= f.cl_image_upload :image %>
  </p>

  <p>
    <%= f.label :blurb %>
    <%= f.text_area :blurb, :id => 'artist_blurb', :maxlength => 100 %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>

  <%= f.submit 'Save profile' %>
<% end %>

app/views/artists/index.html.erb
<h1>Artist#index</h1>
<p>Find me in app/views/artist/index.html.erb</p>

app/views/artists/new.html.erb
<h1>Sign Up</h1>

<% if @artist.errors.any? %>
  <ol>
    <% @artist.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ol>
<% end %>

<%= render :partial => 'form' %>

app/views/artists/show.html.erb
<div id="profile_details">

<h2>Doodler: <%= @artist.name %></h2>

<% if flash[:message].present? %>
  <p><%= flash[:message] %></p>
<% end %>

<% if @artist.id != @current_artist.id %>
  <% if @current_artist.following_ids.include?(@artist.id) %>
   <%= link_to 'Unfollow this Doodler', follow_destroy_path(@artist.id), :method => 'delete' %>
   <% else  %>
   <%= link_to 'Follow this Doodler', follow_new_path(@artist.id) %>
  <% end %>
<% end %>

<!-- <%= image_tag @artist.avatar, :class => 'avatar' %> -->
<%= cl_image_tag(@artist.avatar, :class => 'avatar') %>

<h3>Location: <%= @artist.location %></h3>

<h3>Dob: <%= @artist.dob %></h3>

<h3>Blurb: <%= @artist.blurb %></h3>

</div>

<h3>Here come the doodles:</h3>

<% @doodles.each do |doodle| %>

  <h3>Title: <%= doodle.title %></h3>
  <%= cl_image_tag(doodle.image_url, :class => 'doodle') %>


  <% if doodle.artist_id == @current_artist.id %>
    <div class="controls">
      <%= link_to 'Edit doodle', edit_doodle_path(doodle) %>
      <%= link_to 'Delete doodle', doodle, :method => 'delete', :data => {:confirm => 'Are you sure?'} %>
    </div>
  <% end %>


<% end %>

app/views/artists/update.html.erb
<h1>Artist#update</h1>
<p>Find me in app/views/artist/update.html.erb</p>

app/views/doodles/destroy.html.erb
<h1>Doodle#destroy</h1>
<p>Find me in app/views/doodle/destroy.html.erb</p>

app/views/doodles/edit.html.erb
<h1>Edit</h1>

<%= form_for(@doodle, :html => {:multipart => true}) do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <%= f.submit 'Change title.' %>
<% end %>

app/views/doodles/index.html.erb
<ul>
<% @doodles.each do |doodle| %>
  <li><%= link_to doodle.title, doodle_path(doodle.id) %> by <%= link_to doodle.artist.name, artist_path(doodle.artist.id) if doodle.artist.present? %><br>
  <%= cl_image_tag doodle.image_url, :class => 'doodle' %></li>
<% end %>
</ul>

app/views/doodles/new.html.erb
<h1>New Doodle</h1>

<% if @doodle.errors.any? %>
  <ol>
    <% @doodle.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for(@doodle, :html => {:multipart => true}) do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label "Doodle Image: " %>
    <%= f.cl_image_upload :image %>
  </p>

  <p>
      <%= f.label :caption %>
      <%= f.text_field :caption %>
  </p>

  <%= f.submit 'Submit your new doodle!' %>
<% end %>

app/views/doodles/show.html.erb
<h1><%= @doodle.title %></h1>
<h2><em><%= link_to @doodle.artist.name, @doodle.artist if @doodle.artist %></em></h2>

<%= cl_image_tag(@doodle.image_url, :class => 'doodle_show') %>


<% if @doodle.artist_id == @current_artist.id %>
  <div class="controls">
    <%= link_to 'Edit doodle', edit_doodle_path(@doodle) %>
    <%= link_to 'Delete doodle', @doodle, :method => 'delete', :data => {:confirm => 'Are you sure?'} %>
  </div>
<% end %>

app/views/doodles/update.html.erb
<h1>Doodle#update</h1>
<p>Find me in app/views/doodle/update.html.erb</p>

app/views/follows/create.html.erb
<h1>Follows#create</h1>
<p>Find me in app/views/follows/create.html.erb</p>

app/views/follows/destroy.html.erb
<h1>Follows#destroy</h1>
<p>Find me in app/views/follows/destroy.html.erb</p>

app/views/follows/index.html.erb
<h1>Follows#index</h1>
<p>Find me in app/views/follows/index.html.erb</p>

app/views/follows/show.html.erb
<h1>Follows#show</h1>
<p>Find me in app/views/follows/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doodlr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= cloudinary_js_config %>
</head>
<body class="<%= params[:controller]%>-<%= params[:action] %>">

<div class="container">



<nav class="navbar navbar-light bg-faded">
  <% if @current_artist.present? %>
  <ul class="nav navbar-nav">

    <li class="nav-item active">
      <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
    </li>

    <li class="nav-item">
        <%= link_to 'Profile', artist_path( @current_artist.id ) %>
    </li>

    <li class="nav-item">
        <%= link_to "Edit Account", edit_artist_path(@current_artist.id) %>
    </li>

    <li class="nav-item">
      <%= link_to "Logout: #{ @current_artist.email }", login_path, :method => 'delete' %>
    </li>

  <li class="nav-item">
        <%= link_to 'New Doodle', new_doodle_path %>
    </li>
    <li class="nav-item">
        <%= link_to 'All Doodles', doodles_path %>
    </li>

  </ul>
    <% else %>
      <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      <%= link_to 'Sign up', new_artist_path %>
      <%= link_to 'Sign in', login_path %>
    <% end %>
  </nav>

<%= yield %>

</div>

</body>
</html>

app/views/pages/home.html.erb
<div id="bgimg"></div>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/index.html.erb
<h1>Session#index</h1>
<p>Find me in app/views/session/index.html.erb</p>

app/views/session/new.html.erb
<h1>Sign In</h1>

<% if flash[:message].present? %>
  <h2><%= flash[:message] %></h2>
<% end %>

<%= form_tag login_path do %>
  <%= label_tag :email %>
  <%= email_field_tag :email, nil, :placeholder => 'littledouggie@gmail.com' %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag 'Log in' %>
<% end %>

app/views/session/update.html.erb
<h1>Session#update</h1>
<p>Find me in app/views/session/update.html.erb</p>